// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpAu4ooWcc7BEWnf7btrJDn4Z9o3O531A',
    appId: '1:399404485999:web:aa0b0dced5b43529546c9a',
    messagingSenderId: '399404485999',
    projectId: 'crypto-list-app-7bb94',
    authDomain: 'crypto-list-app-7bb94.firebaseapp.com',
    storageBucket: 'crypto-list-app-7bb94.appspot.com',
    measurementId: 'G-835DJZ0ZZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAscjstV5fd9dGZ1Up_oRZHPX4l438BKzc',
    appId: '1:399404485999:android:870e76d3b089ab28546c9a',
    messagingSenderId: '399404485999',
    projectId: 'crypto-list-app-7bb94',
    storageBucket: 'crypto-list-app-7bb94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGA2ZshmaGe9aYwSs-d86SIUhUeSavPVY',
    appId: '1:399404485999:ios:8a82e0f5c41b518c546c9a',
    messagingSenderId: '399404485999',
    projectId: 'crypto-list-app-7bb94',
    storageBucket: 'crypto-list-app-7bb94.appspot.com',
    iosClientId: '399404485999-v8uoa3afc4pt36aj8jgph28r0hcvv8rh.apps.googleusercontent.com',
    iosBundleId: 'com.need4it.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGA2ZshmaGe9aYwSs-d86SIUhUeSavPVY',
    appId: '1:399404485999:ios:a2ce6288c419c09e546c9a',
    messagingSenderId: '399404485999',
    projectId: 'crypto-list-app-7bb94',
    storageBucket: 'crypto-list-app-7bb94.appspot.com',
    iosClientId: '399404485999-uf5iliugaf2vjf196chu7630ov69ajia.apps.googleusercontent.com',
    iosBundleId: 'com.need4it.cryptoCoinsList.RunnerTests',
  );
}
